# 2. 카드내역 자동정리 프로그램 만들기 with pandas

![shinhan](../images/pandas/shinhancard.png)

In [1]:
import pandas as pd

In [4]:
data = pd.read_excel("data/2020_02_거래내역.xls")#.dropna()
data

,이용일시,승인번호,본인구분,브랜드,이용카드,가맹점명,이용금액,이용구분,매입상태,카테고리
0,2020/02/28 12:14,14073061,본,비자,706,쿠팡,2900,일시불,전표매입,쇼핑
1,2020/02/27 08:41,3311645,본,비자,706,(주) 에이스타커피컴퍼니,5100,일시불,전표매입,커피
2,2020/02/26 22:35,1777639,본,비자,706,(주)우아한형제들,17400,일시불(A),전표매입,야식
3,2020/02/25 18:48,40090458,본,비자,706,하노이별 서강대점,8000,일시불,전표매입,식비
4,2020/02/25 10:02,33240961,본,비자,706,(주) 에이스타커피컴퍼니,5100,일시불,전표매입,커피
...,...,...,...,...,...,...,...,...,...,...
56,2020/02/02 14:06,6544316,본,비자,706,에어프랑스한국지점-BSP,991100,03개월,전표매입,여행
57,2020/02/01 22:21,2751583,본,비자,706,씨유 서강대학사점,3500,일시불,전표매입,식비
58,2020/02/01 18:57,905431,본,비자,706,스타벅스커피코리아,50000,일시불,전표매입,커피
59,2020/02/01 18:44,773794,본,비자,706,개미집,22000,일시불,전표매입,식비
60,2020/02/01 11:04,45363052,본,비자,706,대학약국,6000,일시불,전표매입,생필품

In [5]:
stores = list(data["가맹점명"])
price = list(data["이용금액"])
categories = list(data["카테고리"])

In [7]:
print(len(data["가맹점명"])) # 61이어야 합니다.
print(len(set(data["가맹점명"])))

61
38

In [11]:
target = pd.read_excel("data/2020_03_거래내역.xls").dropna().reset_index(drop=True)
target

,이용일시,승인번호,본인구분,브랜드,이용카드,가맹점명,이용금액,이용구분,매입상태
0,2020/03/22 22:38,35114626,본,비자,706,지에스25 뉴서강대학사점,7650,일시불,전표매입
1,2020/03/22 20:29,34371480,본,비자,706,(주)브로일링커피컴퍼니,10000,일시불,전표매입
2,2020/03/22 20:08,34198250,본,비자,706,김밥천국,6000,일시불,전표매입
3,2020/03/22 18:48,33504221,본,비자,706,(주)현대백화점 신촌점,35000,일시불,전표매입
4,2020/03/22 14:43,31106136,본,비자,706,일월일일(一月一日),17500,일시불,전표매입
...,...,...,...,...,...,...,...,...,...
85,2020/02/26 22:35,1777639,본,비자,706,(주)우아한형제들,17400,일시불(A),전표매입
86,2020/02/25 18:48,40090458,본,비자,706,하노이별 서강대점,8000,일시불,전표매입
87,2020/02/25 10:02,33240961,본,비자,706,(주) 에이스타커피컴퍼니,5100,일시불,전표매입
88,2020/02/24 21:09,30550169,본,비자,706,(주)우아한형제들,13800,일시불(A),전표매입
89,2020/02/23 07:59,14813880,본,비자,706,(주)커피빈코리아인천공항제2여,6800,일시불,전표매입

In [16]:
target_categories = [] # 3월 거래내역에 추가될 "카테고리" 정보.
target_stores = list(target["가맹점명"])
target_price = list(target["이용금액"])

for store in target_stores:
    """
    3월 거래내역에 있는 가맹점명을 순서대로 하나씩 보면서,
    해당 가맹점명이 포함된 2월달 거래내역의 카테고리를 3월 거래내역에 추가하면 됩니다.
    
    3월 첫번째 거래내역 -> 2월 거래내역의 몇번째(index)인지 확인 -> 해당 index의 category를 가져옴.
    -> target_categories에 추가. -> .....
    """
    #print(store)
    # "지에스25 뉴서강대학사점"
    try:
        idx = stores.index(store) # store라는 원소가 stores라는 리스트에 어디(index)에 있는지 알려줍니다.
        temp = categories[idx] # 2월달 해당 가맹점명을 가지는 거래내역의 카테고리
    except ValueError:
        temp = "미정" # 3월 거래내역의 가맹점명이 2월 거래내역에 존재하지 않는 경우.
        
    target_categories.append(temp)

In [17]:
target["카테고리"] = target_categories

In [18]:
target.head()

,이용일시,승인번호,본인구분,브랜드,이용카드,가맹점명,이용금액,이용구분,매입상태,카테고리
0,2020/03/22 22:38,35114626,본,비자,706,지에스25 뉴서강대학사점,7650,일시불,전표매입,식비
1,2020/03/22 20:29,34371480,본,비자,706,(주)브로일링커피컴퍼니,10000,일시불,전표매입,커피
2,2020/03/22 20:08,34198250,본,비자,706,김밥천국,6000,일시불,전표매입,미정
3,2020/03/22 18:48,33504221,본,비자,706,(주)현대백화점 신촌점,35000,일시불,전표매입,쇼핑
4,2020/03/22 14:43,31106136,본,비자,706,일월일일(一月一日),17500,일시불,전표매입,미정

In [19]:
target[target["카테고리"] == "미정"]

,이용일시,승인번호,본인구분,브랜드,이용카드,가맹점명,이용금액,이용구분,매입상태,카테고리
2,2020/03/22 20:08,34198250,본,비자,706,김밥천국,6000,일시불,전표매입,미정
4,2020/03/22 14:43,31106136,본,비자,706,일월일일(一月一日),17500,일시불,전표매입,미정
5,2020/03/22 13:33,30442459,본,비자,706,자판기1,1500,일시불,전표매입,미정
6,2020/03/21 14:26,22395683,본,비자,706,(주)이앤지커피,4000,일시불,전표매입,미정
9,2020/03/20 18:04,15105779,본,비자,706,공차 서강대점,4500,일시불,전표매입,미정
12,2020/03/20 10:56,10268549,본,비자,706,미소가인피부과 아현점,11000,일시불,전표매입,미정
16,2020/03/19 14:39,1740605,본,비자,706,GS25용산신계점,1200,일시불,전표매입,미정
20,2020/03/18 19:16,45275159,본,비자,706,새문순대국,8000,일시불,전표매입,미정
23,2020/03/17 18:05,34469894,본,비자,706,한솥서강대점,5300,일시불,전표매입,미정
25,2020/03/16 16:47,24646370,본,비자,706,공차 서강대점,4500,일시불,전표매입,미정
29,2020/03/15 17:39,15424381,본,비자,706,신촌돈부리모노신촌2호점,8000,일시불,전표매입,미정
30,2020/03/14 22:47,10045120,본,비자,706,씨유 마포월드점,2150,일시불,전표매입,미정
31,2020/03/14 19:43,8701550,본,비자,706,장고네라라옥,34000,일시불,전표매입,미정
33,2020/03/14 14:19,5181621,본,비자,706,CU 서강대점,1600,일시불,전표매입,미정
36,2020/03/14 09:53,2475384,본,비자,706,(주) 코리아세븐 서강대르메이에,3800,일시불,전표매입,미정
41,2020/03/12 18:00,38226713,본,비자,706,포냐 서강대점,7000,일시불,전표매입,미정
45,2020/03/11 21:39,30104635,본,비자,706,크라우드 대흥역점,4500,일시불,전표매입,미정
47,2020/03/11 13:01,24839440,본,비자,706,주식회사 미분당,21500,일시불,전표매입,미정
48,2020/03/11 00:48,20734599,본,비자,706,티머니 법인택시,16500,일시불,전표매입,미정
49,2020/03/10 13:17,14913380,본,비자,706,샐러디 서강대점,5310,일시불,전표매입,미정
54,2020/03/09 18:22,8051049,본,비자,706,돈카츠윤석,31000,일시불,전표매입,미정
56,2020/03/09 11:35,3241106,본,비자,706,마포만두,7500,일시불,전표매입,미정
57,2020/03/09 10:55,2033624,본,비자,706,미소가인피부과 아현점,11000,일시불,전표매입,미정
60,2020/03/08 19:51,47925328,본,비자,706,QUENCH COFFEE,21000,일시불,전표매입,미정
61,2020/03/08 18:14,47051437,본,비자,706,대흥365약국,5000,일시불,전표매입,미정
70,2020/03/06 15:34,28522024,본,비자,706,서강안경,89600,일시불,전표매입,미정
72,2020/03/05 22:54,23314365,본,비자,706,CU 서강대점,3400,일시불,전표매입,미정
74,2020/03/05 18:50,21383161,본,비자,706,충화반점,8900,일시불,전표매입,미정
75,2020/03/05 15:08,19106226,본,비자,706,샐러디 서강대점,5310,일시불,전표매입,미정
77,2020/03/04 19:41,12814527,본,비자,706,돈카츠윤석,31500,일시불,전표매입,미정
78,2020/03/04 15:01,10044333,본,비자,706,주식회사 비에이에이치앤,27000,일시불,전표매입,미정
82,2020/03/02 16:16,42637878,본,비자,706,네이버페이,26100,일시불,전표매입,미정

In [20]:
target.to_excel("data/거래내역(정리).xlsx")

In [22]:
result = pd.DataFrame({"가맹점명" : stores, "이용금액" : price, "계정과목" : categories})
result

             가맹점명    이용금액 계정과목
0              쿠팡    2900   쇼핑
1   (주) 에이스타커피컴퍼니    5100   커피
2       (주)우아한형제들   17400   야식
3       하노이별 서강대점    8000   식비
4   (주) 에이스타커피컴퍼니    5100   커피
..            ...     ...  ...
56  에어프랑스한국지점-BSP  991100   여행
57      씨유 서강대학사점    3500   식비
58      스타벅스커피코리아   50000   커피
59            개미집   22000   식비
60           대학약국    6000  생필품

[61 rows x 3 columns]